# Generated by Django 3.1.4 on 2021-01-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='DEPARTMENT_ID',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='workers',
            name='MANAGER_ID',
            field=models.IntegerField(default=None),
        ),
    ]
