# Generated by Django 3.1.4 on 2021-01-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20210102_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
