# Generated by Django 3.1.4 on 2021-01-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_workers_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
